title: Welcome
author: GitHub User / Arserom
email: cnguyen1209@unm.edu
description: > # this means to ignore newlines until "baseurl:"
HOlla

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
