title: Welcome
author: GitHub User / Arserom
email: cnguyen1209@unm.edu
description: > # this means to ignore newlines until "baseurl:"
zxczxczxczxczxczxczxczxc

# social links
twitter_username: dfsf
github_username:  zxczxc

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
